# Bunlar desteklenen finansman modeli platformlarıdır

github: # En fazla 4 GitHub Sponsorunun etkin olduğu kullanıcı adıyla değiştirin, ör. [user1, user2]
patreon: # Tek bir Patreon kullanıcı adıyla değiştirin
